node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/SyCode7/spring-petclinic-microservices-swagger.git', credentialsId: 'SyCode7-@secure&sons7', branch: 'master'
        }

        stage('Build') {
            sh 'mvn install -DskipTests'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('spring-petclinic-discovery-server') {
                def app = docker.build "localhost:5000/spring-petclinic-discovery-server:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:5000/spring-petclinic-discovery-server:${env.version}").run('-p 8761:8761 -h discovery --name discovery')
        }

        stage ('Final') {
            build job: 'spring-petclinic-customers-service', wait: false
        }  

    }

}
